-- Table to store WebAuthn credentials (passkeys) for step-up authentication.
-- The webauthn_user_handle is a stable random identifier that maps a Sourcegraph user
-- to a WebAuthn user ID. All credentials for the same user share the same handle.
CREATE TABLE IF NOT EXISTS user_webauthn_credentials (
    id BIGSERIAL PRIMARY KEY,
    tenant_id INTEGER NOT NULL DEFAULT current_setting('app.current_tenant')::integer,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    webauthn_user_handle BYTEA NOT NULL,
    credential_id BYTEA NOT NULL,
    public_key BYTEA NOT NULL,
    sign_count BIGINT NOT NULL DEFAULT 0,
    aaguid BYTEA NULL,
    attestation_type TEXT NOT NULL DEFAULT '',
    transports TEXT[] NOT NULL DEFAULT '{}',
    backup_eligible BOOLEAN NOT NULL DEFAULT false,
    backup_state BOOLEAN NOT NULL DEFAULT false,
    user_verified BOOLEAN NOT NULL DEFAULT false,
    nickname TEXT NOT NULL DEFAULT '',
    last_used_at TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    revoked_at TIMESTAMP WITH TIME ZONE NULL,
    -- Attestation data for later verification
    attestation_object BYTEA NULL,
    attestation_client_data_hash BYTEA NULL,
    public_key_algorithm BIGINT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS user_webauthn_credentials_tenant_credential_idx
    ON user_webauthn_credentials (tenant_id, credential_id);

CREATE INDEX IF NOT EXISTS user_webauthn_credentials_tenant_user_active_idx
    ON user_webauthn_credentials (tenant_id, user_id)
    WHERE revoked_at IS NULL;

ALTER TABLE user_webauthn_credentials ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_policy ON user_webauthn_credentials;
CREATE POLICY tenant_isolation_policy ON user_webauthn_credentials AS PERMISSIVE FOR ALL TO PUBLIC
    USING (tenant_id = (SELECT current_setting('app.current_tenant')::integer AS current_tenant));

COMMENT ON TABLE user_webauthn_credentials IS 'Stores WebAuthn/FIDO2 passkey credentials for step-up authentication. Users can register passkeys to verify identity before sensitive operations.';
COMMENT ON COLUMN user_webauthn_credentials.webauthn_user_handle IS 'Stable random identifier (32 bytes) mapping the Sourcegraph user to a WebAuthn user ID. All credentials for the same user share the same handle.';
COMMENT ON COLUMN user_webauthn_credentials.credential_id IS 'Unique identifier for this credential, generated by the authenticator during registration.';
COMMENT ON COLUMN user_webauthn_credentials.public_key IS 'COSE-encoded public key for verifying authentication signatures.';
COMMENT ON COLUMN user_webauthn_credentials.sign_count IS 'Signature counter from the authenticator, used to detect cloned credentials.';
COMMENT ON COLUMN user_webauthn_credentials.aaguid IS 'Authenticator Attestation GUID identifying the authenticator model.';
COMMENT ON COLUMN user_webauthn_credentials.transports IS 'Supported transport methods (usb, nfc, ble, internal, hybrid).';
COMMENT ON COLUMN user_webauthn_credentials.backup_eligible IS 'Whether the credential can be backed up (e.g., synced passkeys).';
COMMENT ON COLUMN user_webauthn_credentials.backup_state IS 'Whether the credential is currently backed up.';
COMMENT ON COLUMN user_webauthn_credentials.revoked_at IS 'Soft-delete timestamp. Non-null means the credential is revoked and cannot be used.';
