CREATE OR REPLACE FUNCTION migrate_tenant_id_non_null_frontend_down(table_name text)
RETURNS void AS $$
BEGIN
    EXECUTE format('ALTER TABLE %I DROP COLUMN IF EXISTS tenant_id;', table_name);
    EXECUTE format('ALTER TABLE %I ADD COLUMN tenant_id integer DEFAULT 1 REFERENCES tenants(id) ON UPDATE CASCADE ON DELETE CASCADE;', table_name);
END;
$$ LANGUAGE plpgsql;

SELECT migrate_tenant_id_non_null_frontend_down('access_requests'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('access_tokens'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('aggregated_user_statistics'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('assigned_owners'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('assigned_teams'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('batch_changes'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('batch_changes_site_credentials'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('batch_spec_execution_cache_entries'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('batch_spec_resolution_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('batch_spec_workspace_execution_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('batch_spec_workspace_execution_last_dequeues'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('batch_spec_workspace_files'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('batch_spec_workspaces'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('batch_specs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('cached_available_indexers'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('changeset_events'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('changeset_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('changeset_specs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('changesets'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('cm_action_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('cm_emails'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('cm_last_searched'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('cm_monitors'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('cm_queries'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('cm_recipients'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('cm_slack_webhooks'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('cm_trigger_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('cm_webhooks'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('code_hosts'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('codeintel_autoindex_queue'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('codeintel_autoindexing_exceptions'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('codeowners'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('codeowners_individual_stats'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('codeowners_owners'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('commit_authors'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('context_detection_embedding_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('discussion_comments'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('discussion_mail_reply_tokens'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('discussion_threads'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('discussion_threads_target_repo'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('event_logs_export_allowlist'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('event_logs_scrape_state'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('event_logs_scrape_state_own'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('executor_heartbeats'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('executor_job_tokens'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('executor_secret_access_logs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('executor_secrets'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('exhaustive_search_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('exhaustive_search_repo_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('exhaustive_search_repo_revision_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('explicit_permissions_bitbucket_projects_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('external_services'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('github_app_installs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('github_apps'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('gitserver_relocator_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('gitserver_repos'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('gitserver_repos_sync_output'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('global_state'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('insights_query_runner_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('insights_query_runner_jobs_dependencies'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('lsif_configuration_policies'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('lsif_configuration_policies_repository_pattern_lookup'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('lsif_dependency_indexing_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('lsif_dependency_repos'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('lsif_dependency_syncing_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('lsif_dirty_repositories'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('lsif_index_configuration'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('lsif_indexes'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('lsif_last_retention_scan'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('lsif_packages'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('lsif_retention_configuration'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('lsif_uploads'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('lsif_uploads_vulnerability_scan'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('names'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('namespace_permissions'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('notebook_stars'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('notebooks'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('org_invitations'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('org_members'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('org_stats'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('orgs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('out_of_band_migrations_errors'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('outbound_webhook_event_types'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('outbound_webhook_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('outbound_webhook_logs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('outbound_webhooks'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('own_aggregate_recent_contribution'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('own_aggregate_recent_view'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('own_background_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('own_signal_configurations'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('own_signal_recent_contribution'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('ownership_path_stats'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('package_repo_filters'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('package_repo_versions'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('permission_sync_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('permissions'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('phabricator_repos'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('prompts'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('registry_extension_releases'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('registry_extensions'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('repo'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('repo_commits_changelists'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('repo_context_stats'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('repo_context_stats_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('repo_embedding_job_stats'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('repo_embedding_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('repo_kvps'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('repo_paths'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('role_permissions'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('roles'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('saved_searches'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('search_context_default'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('search_context_stars'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('search_contexts'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('settings'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('survey_responses'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('syntactic_scip_indexing_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('team_members'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('teams'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('telemetry_events_export_queue'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('temporary_settings'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('user_credentials'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('user_external_accounts'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('user_onboarding_tour'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('user_repo_permissions'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('user_roles'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('users'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('vulnerabilities'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('vulnerability_affected_packages'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('vulnerability_affected_symbols'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('vulnerability_matches'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('webhook_logs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('webhooks'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('zoekt_repos'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('repo_pending_permissions'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('repo_permissions'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('search_context_repos'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('user_emails'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('lsif_uploads_reference_counts'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('external_service_repos'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('external_service_sync_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('sub_repo_permissions'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('codeintel_commit_dates'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('codeintel_inference_scripts'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('codeintel_langugage_support_requests'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('configuration_policies_audit_logs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('event_logs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('feature_flags'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('feature_flag_overrides'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('gitserver_repos_statistics'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('insights_settings_migration_jobs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('lsif_last_index_scan'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('lsif_nearest_uploads'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('lsif_nearest_uploads_links'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('lsif_references'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('lsif_uploads_audit_logs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('lsif_uploads_visible_at_tip'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('query_runner_state'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('repo_statistics'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('security_event_logs'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('user_pending_permissions'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('user_permissions'); COMMIT AND CHAIN;
SELECT migrate_tenant_id_non_null_frontend_down('syntactic_scip_last_index_scan'); COMMIT AND CHAIN;

ALTER TABLE batch_changes ALTER COLUMN tenant_id SET NOT NULL; COMMIT AND CHAIN;
ALTER TABLE batch_changes ALTER COLUMN tenant_id SET DEFAULT (COALESCE(current_setting('app.current_tenant'::text, true), '1'::text))::integer; COMMIT AND CHAIN;
ALTER TABLE discussion_mail_reply_tokens ALTER COLUMN tenant_id SET NOT NULL; COMMIT AND CHAIN;
ALTER TABLE discussion_mail_reply_tokens ALTER COLUMN tenant_id SET DEFAULT (COALESCE(current_setting('app.current_tenant'::text, true), '1'::text))::integer; COMMIT AND CHAIN;
ALTER TABLE feature_flags ALTER COLUMN tenant_id SET NOT NULL; COMMIT AND CHAIN;
ALTER TABLE feature_flags ALTER COLUMN tenant_id SET DEFAULT (COALESCE(current_setting('app.current_tenant'::text, true), '1'::text))::integer; COMMIT AND CHAIN;
ALTER TABLE names ALTER COLUMN tenant_id SET NOT NULL; COMMIT AND CHAIN;
ALTER TABLE names ALTER COLUMN tenant_id SET DEFAULT (COALESCE(current_setting('app.current_tenant'::text, true), '1'::text))::integer; COMMIT AND CHAIN;
ALTER TABLE syntactic_scip_last_index_scan ALTER COLUMN tenant_id SET NOT NULL; COMMIT AND CHAIN;
ALTER TABLE syntactic_scip_last_index_scan ALTER COLUMN tenant_id SET DEFAULT (COALESCE(current_setting('app.current_tenant'::text, true), '1'::text))::integer; COMMIT AND CHAIN;

CREATE UNIQUE INDEX tmp_unique_index ON batch_changes (name, namespace_org_id, tenant_id) WHERE namespace_org_id IS NOT NULL;
DROP INDEX IF EXISTS batch_changes_unique_org_id;
ALTER INDEX tmp_unique_index RENAME TO batch_changes_unique_org_id;
COMMIT AND CHAIN;

CREATE UNIQUE INDEX tmp_unique_index ON batch_changes (name, namespace_user_id, tenant_id) WHERE namespace_user_id IS NOT NULL;
DROP INDEX IF EXISTS batch_changes_unique_user_id;
ALTER INDEX tmp_unique_index RENAME TO batch_changes_unique_user_id;
COMMIT AND CHAIN;

ALTER TABLE discussion_mail_reply_tokens DROP CONSTRAINT IF EXISTS discussion_mail_reply_tokens_pkey;
ALTER TABLE discussion_mail_reply_tokens ADD PRIMARY KEY (token, tenant_id);
COMMIT AND CHAIN;

ALTER TABLE feature_flags DROP CONSTRAINT IF EXISTS feature_flags_pkey;
ALTER TABLE feature_flags ADD PRIMARY KEY (flag_name, tenant_id);
COMMIT AND CHAIN;

ALTER TABLE names DROP CONSTRAINT IF EXISTS names_pkey;
ALTER TABLE names ADD PRIMARY KEY (name, tenant_id);
COMMIT AND CHAIN;

ALTER TABLE syntactic_scip_last_index_scan DROP CONSTRAINT IF EXISTS syntactic_scip_last_index_scan_pkey;
ALTER TABLE syntactic_scip_last_index_scan ADD PRIMARY KEY (repository_id, tenant_id);
COMMIT AND CHAIN;

DO $$
BEGIN
  BEGIN
    ALTER TABLE global_state ADD CONSTRAINT global_state_site_id_unique UNIQUE (site_id, tenant_id);
  EXCEPTION
    WHEN duplicate_table THEN  -- postgres raises duplicate_table at surprising times. Ex.: for UNIQUE constraints.
    WHEN duplicate_object THEN
      RAISE NOTICE 'Table constraint global_state_site_id_unique already exists, skipping';
  END;
END $$;
COMMIT AND CHAIN;

DROP FUNCTION migrate_tenant_id_non_null_frontend_down(text);
