ALTER TABLE archived_insight_series_recording_times ALTER COLUMN tenant_id SET DEFAULT 1; COMMIT AND CHAIN;

ALTER TABLE archived_series_points ALTER COLUMN tenant_id SET DEFAULT 1; COMMIT AND CHAIN;

ALTER TABLE dashboard ALTER COLUMN tenant_id SET DEFAULT 1; COMMIT AND CHAIN;

ALTER TABLE dashboard_grants ALTER COLUMN tenant_id SET DEFAULT 1; COMMIT AND CHAIN;

ALTER TABLE dashboard_insight_view ALTER COLUMN tenant_id SET DEFAULT 1; COMMIT AND CHAIN;

ALTER TABLE insight_series ALTER COLUMN tenant_id SET DEFAULT 1; COMMIT AND CHAIN;

ALTER TABLE insight_series_backfill ALTER COLUMN tenant_id SET DEFAULT 1; COMMIT AND CHAIN;

ALTER TABLE insight_series_incomplete_points ALTER COLUMN tenant_id SET DEFAULT 1; COMMIT AND CHAIN;

ALTER TABLE insight_series_recording_times ALTER COLUMN tenant_id SET DEFAULT 1; COMMIT AND CHAIN;

ALTER TABLE insight_view ALTER COLUMN tenant_id SET DEFAULT 1; COMMIT AND CHAIN;

ALTER TABLE insight_view_grants ALTER COLUMN tenant_id SET DEFAULT 1; COMMIT AND CHAIN;

ALTER TABLE insight_view_series ALTER COLUMN tenant_id SET DEFAULT 1; COMMIT AND CHAIN;

ALTER TABLE insights_background_jobs ALTER COLUMN tenant_id SET DEFAULT 1; COMMIT AND CHAIN;

ALTER TABLE insights_data_retention_jobs ALTER COLUMN tenant_id SET DEFAULT 1; COMMIT AND CHAIN;

ALTER TABLE metadata ALTER COLUMN tenant_id SET DEFAULT 1; COMMIT AND CHAIN;

ALTER TABLE repo_iterator ALTER COLUMN tenant_id SET DEFAULT 1; COMMIT AND CHAIN;

ALTER TABLE repo_iterator_errors ALTER COLUMN tenant_id SET DEFAULT 1; COMMIT AND CHAIN;

ALTER TABLE repo_names ALTER COLUMN tenant_id SET DEFAULT 1; COMMIT AND CHAIN;

ALTER TABLE series_points ALTER COLUMN tenant_id SET DEFAULT 1; COMMIT AND CHAIN;

ALTER TABLE series_points_snapshots ALTER COLUMN tenant_id SET DEFAULT 1;
