-- Do nothing because this migration only exists to unify an edited migration with it's initial state
-- after the up is applied it should fix the bad state of instances that saw the old migration. We don't
-- want to revert to that bad state
