name: Check for new artifacts

on:
  workflow_dispatch:

  schedule:
    # https://crontab.guru/#0_7_*_*_*
    # Every saturday at 7am
    - cron: '0 7 * * *'

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4 